---
- name: Deps 4 JupyterHub notebook
  apt: name={{ item }}
  with_items:
    - npm
    - nodejs
    - nodejs-legacy
    - python3-pip
    - python-pip
    - libffi-dev
- name: configurable-http-proxy
  npm: name=configurable-http-proxy global=yes
- name: Jupyter for Python 3
  pip: name=jupyter executable=pip3
- name: Jupyter-client downgrade for Python 3
  pip: name=jupyter-client executable=pip3 version==4.4.0
- name: Jupyter-client downgrade for Python 2.7
  pip: name=jupyter-client executable=pip version==4.4.0
- name: ipykernel for Python 2
  pip: name=ipykernel executable=pip
- name: Python 2 to Jupyter
  shell: /usr/bin/python2 -m ipykernel install creates=/usr/local/share/jupyter/kernels/python2
- name: Toree (Spark Jupyter)
  include: toree.yml
- name: JupyterHub
  pip: name=jupyterhub executable=pip3
- name: /etc/jupyterhub
  file: path=/etc/jupyterhub state=directory
- name: JupyterHub config
  command: jupyterhub --generate-config -f /etc/jupyterhub/jupyterhub_config.py creates=/etc/jupyterhub/jupyterhub_config.py
- name: Bind JupyterHub to all interfaces
  blockinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    block: |
      c.JupyterHub.ip = '0.0.0.0'
# Default hub_port in use by Spark
- name: Bind JupyterHub to port 8011
  blockinfile:
    dest: /etc/jupyterhub/jupyterhub_config.py
    block: |
      c.JupyterHub.hub_port = 8011
- name: Start/stop script JupyterHub
  copy: src=jupyterhub.systemd dest=/etc/systemd/system/jupyterhub.service
- name: JupyterHub started
  systemd: name=jupyterhub state=started daemon_reload=yes
