---
- name: Spark home
  file:
    name: '{{ spark_home }}'
    state: directory
- name: Spark distro
  unarchive:
    src: '{{ spark_tarball }}'
    dest: '{{ spark_parent }}'
    remote_src: True
- name: Spark config slaves
  template:
    src: slaves.j2
    dest: '{{ spark_home }}/conf/slaves'
- name: Spark defaults
  blockinfile:
    dest: '{{ spark_home }}/conf/spark-defaults.conf'
    create: yes
    block: |
      spark.master    spark://{{ inventory_hostname }}:7077
      spark.shuffle.service.enabled true
      spark.dynamicAllocation.enabled   true
      spark.dynamicAllocation.initialExecutors  4
- name: Copy start-master.systemd
  template: src=spark-master.systemd.j2 dest=/etc/systemd/system/spark-master.service
- name: Spark-master started
  systemd: name=spark-master state=started daemon_reload=yes
- include: jupyter.yml
