---
cran_url: http://cran-mirror.cs.uu.nl
cran_ppa_key: E084DAB9
spark_tarball: http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz
spark_parent: /data/shared/spark
spark_home: /data/shared/spark/spark-2.1.0-bin-hadoop2.7
